#!/usr/bin/python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

import os
import sys 
sys.path.append(os.path.abspath("/usr/lib/waggle/plugin_manager/plugins/alphasense"))
from alphasense import *

if __name__ == '__main__':

    alphasense = Alphasense('/dev/alphasense')
    sleep(3)

    version = alphasense.get_firmware_version()
    sleep(1)

    sn = alphasense.get_serial_number()
    sleep(1)
    if sn[0] == 0xff:
      sn=bytearray([0x30]*16)

    print('Firmware Version: ', version[24:28].decode('utf-8')[:28])
    print('Alphasense_id: ', sn[7:].decode('utf-8'))

    alphasense.close()
