#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $script_dir/utils.sh

if [ $# -ne 2 ]; then
	exit 1
elif [[ "$0" != "emmc" && "$0"  "sd" ]]; then
	exit 2
elif [[ "$1" -ne "nc" && "$1" -ne "ep" ]]; then
	exit 3
fi

echo "Waiting for waggle-init to finish..."
wait_for_init

port=''
if [ "$1" -eq "nc" ]; then
	port='0'
elif [ "$1" -eq "ep" ]; then
	port='1'
else
	exit 4
fi

echo "Setting ${$0^^} boot disk to $0..."
wagman-client bs $port $0

echo "Requesting ${$0^^} reboot..."
wagman-client stop $port 60