#!/usr/bin/env python

import pika
import time

def callback(channel, method, properties, body):
    logging.info("Received build request: %r" % body)
    logging.info("Downloading ODroid base image...")
    logging.info("Downloading Waggle base image...")
    logging.info("Building Waggle Node Controller image...")
    logging.info("Build complete.")
    channel.basic_ack(delivery_tag = method.delivery_tag)

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

'''
credentials = pika.credentials.PlainCredentials('node', 'waggle')
ssl_options={'ca_certs':'/usr/lib/waggle/SSL/waggleca/cacert.pem',
             'certfile':'/usr/lib/waggle/SSL/node/cert.pem',
             'keyfile':'/usr/lib/waggle/SSL/node/key.pem'}

connection = pika.BlockingConnection(pika.ConnectionParameters(
  host='beehive', port=23181, credentials=credentials, ssl=True,
  ssl_options=ssl_options, socket_timeout=10))
'''
connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost'))
channel = connection.channel()

channel.queue_declare(queue='build', durable=True)

channel.basic_qos(prefetch_count=1)
channel.basic_consume(callback,
                      queue='task_queue')

logging.info("waggle-build service is listening for build tasks...")
channel.start_consuming()
