#!/bin/bash
echo
echo "___Coresense Flashing Utility___"
echo
if [ $# -eq 0 ]
then
    echo "No Coresense firmware file provided."
    echo "Correct usage - coresenseflash firmware.ino.bin"
    echo
    exit
fi

if [ ${1: -8} != ".ino.bin" ]
then
    echo "Incorrect Coresense firmware file provided. The firmware file has .ino.bin extension."
    echo
    exit
fi

coresense-plugin=$(systemctl is-active waggle-plugin-coresense.service)
if [ "${coresense-plugin}" != "inactive" ]
then
    echo "Stopping waggle-plugin-coresense.service..."
    systemctl stop waggle-plugin-coresense.service
    if [ $? -nq 0 ]
    then
        echo "Could not stop waggle-plugin-coresense.service. Please stop the service manually and try again."
        echo
        exit
    fi
fi

if [ -e "/dev/waggle_coresense" ]
then
    echo "Resetting Coresense board to bootloader mode... (Step 1/2)"
    echo
    stty -F /dev/waggle_coresense 1200 hupcl; sleep 2
    echo "Flashing Coresense board with new firmware... (Step 2/2)"
    echo
    /usr/bin/bossac -i -d --port=waggle_coresense -U true -e -w -v -b $1 -R
    echo 
    echo "############ Firmware flash process completed #############"
    echo
else 
    echo "Coresense device not found."
fi

if [ "${coresense-plugin}" != "inactive" ]
then
    sleep 3
    echo "Restarting waggle-plugin-coresense.service..."
    systemctl start waggle-plugin-coresense.service
fi
