#!/bin/sh
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

/usr/lib/waggle/nodecontroller/scripts/modem_info.py $(ls /dev/attwwan?* | sort | sed -n '4p')
