#!/usr/bin/env python3
from serial import Serial
import sys
import time

while True:
    try:
        s = Serial(sys.argv[1])
        break
    except:
        time.sleep(1)

s.write(b'AT+CGSN\r')

s.readline()
print('+IMEI:', s.readline().decode().strip())
s.readline()
s.readline()

s.write(b'AT+CCID\r')

s.readline()
print(s.readline().decode().strip())
s.readline()
s.readline()

print()
