#!/usr/bin/python3

import logging
import os
import threading
import time
import zmq

class NodeControllerShutdownThread(threading.Thread):
  def __init__(self):
    threading.Thread.__init__(self, group=None, target=None, name=None)
    self.wait_for_ep = False

  def run(self):
    logging.info("Wagman is cycling the node controller power in one minute; shutdown in 30 seconds")
    os.system("shutdown -h -k +1")
    time.sleep(30)
    while self.wait_for_ep:
      logging.info("waiting 1 second for Edge Processor to shutdown...")
      time.sleep(1)
    logging.info("node controller shutting down now")
    os.system("shutdown -h now")

class EdgeProcessorShutdownThread(threading.Thread):
  def __init__(self, nc_stopper):
    threading.Thread.__init__(self, group=None, target=None, name=None)
    self.nc_stopper = nc_stopper

  def run(self):
    self.nc_stopper.wait_for_ep = True
    logging.info("Wagman is cycling the Edge Processor power in one minute; shutdown in 30 seconds")
    os.system('/usr/lib/waggle/nodecontroller/scripts/eplogin shutdown -h -k +1')
    time.sleep(30)
    logging.info("Edge Processor shutting down now")
    os.system('/usr/lib/waggle/nodecontroller/scripts/eplogin shutdown -h now')
    self.nc_stopper.wait_for_ep = False

def subscribe_wagman_status():
  context = zmq.Context()
  socket = context.socket(zmq.SUB)
  socket.setsockopt(zmq.RCVTIMEO, 5000)
  socket.setsockopt(zmq.SUBSCRIBE, b'')
  socket.connect ('ipc:///tmp/zeromq_wagman-pub')
  return socket

def unsubscribe_wagman_status(socket):
  socket.close()

# Check for shutdown messages
def check_wagman_shutdown(socket):
  message = ""
  try:
    message = socket.recv_string()
    if 'nc stopp' in message:
      return "nc"
    elif 'gn stopp' in message:
      return "ep"
  except zmq.ZMQError:
    pass
  return 'no'

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
wagman_status = subscribe_wagman_status()

logging.info("waggle-shutdown-monitor service is running...")

nc_stopper = NodeControllerShutdownThread()
ep_stopper = EdgeProcessorShutdownThread(nc_stopper)
while True:
  shutdown = check_wagman_shutdown(wagman_status)
  if (shutdown == 'nc' and not nc_stopper.isAlive()):
    nc_stopper.start()
  elif (shutdown == 'ep' and not ep_stopper.isAlive()):
    ep_stopper.start()
  time.sleep(1)
