#!/usr/bin/python3
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license
from pathlib import Path
import socket
import time
import subprocess


# using /run as some older nodes don't mount /tmp as tmpfs
# /run seems to be more consistently used this way
def reset_deadman_trigger():
    print('reset deadman trigger', flush=True)
    Path('/run/waggle_deadman_trigger').touch()


def reset_deadman_trigger_for_duration(duration):
    start = time.monotonic()

    while time.monotonic() - start < duration:
        reset_deadman_trigger()
        time.sleep(15)


def has_connectivity():
    try:
        return 'ESTABLISHED' in subprocess.check_output(['lsof', '-i', 'TCP@beehive:20022']).decode()
    except Exception:
        return False


while True:
    while not has_connectivity():
        print('waiting for connection', flush=True)
        time.sleep(900)
    print('connection ok', flush=True)
    reset_deadman_trigger_for_duration(3600)
