#!/usr/bin/env python3
from pathlib import Path
import subprocess
import time
import logging

logging.basicConfig(level=logging.INFO)


def connection_ok():
    try:
        return 'ESTABLISHED' in subprocess.check_output(['lsof', '-i', 'TCP@beehive:20022']).decode()
    except Exception:
        return False


connectivity_services = [
    'waggle-wwan.service',
    'waggle-reverse-tunnel.service',
]


def reset_connectivity_services():
    for service in connectivity_services:
        try:
            subprocess.check_output(['systemctl', 'restart', service])
        except Exception:
            logging.exception('failed to restart service %s', service)


def reset_deadman_trigger():
    Path('/run/waggle_deadman_trigger').touch()


last_connection_time = time.monotonic()
reset_timeout = time.monotonic()

while True:
    if connection_ok():
        logging.info('connection ok')
        last_connection_time = time.monotonic()
        reset_timeout = time.monotonic()
    else:
        left = int(time.monotonic() - last_connection_time)
        logging.warning('no connection for %ss', left)

    # continue updating deadman trigger up to an hour after last connection
    if time.monotonic() - last_connection_time < 3600:
        logging.info('update deadman trigger')
        reset_deadman_trigger()

    # attempt to reset reverse ssh tunnel after 15min of no connectivity
    if time.monotonic() - reset_timeout > 900:
        logging.warning('reset connectivity services')
        reset_connectivity_services()
        reset_timeout = time.monotonic()

    time.sleep(15)
