#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $script_dir/utils.sh

echo "Waiting for waggle-init to finish..."
wait_for_init

echo "Requesting reboot of Edge Processor"
wagman-client stop 1 60 || true

echo "Requesting reboot of Node Controller"
wagman-client stop 0 60 || true