#!/bin/bash

run_tests() {
  echo "Running tests..."
  /usr/lib/waggle/nodecontroller/scripts/test_node.sh \
    > /home/waggle/test_node_NC_${CURRENT_DISK_DEVICE_TYPE}.log
}

generate_report() {
  echo "In generate_report"
  local report_file="/home/waggle/test-report.txt"
  echo "Node Controller eMMC Test Results" > $report_file
  echo "-------------------------------" >> $report_file
  cat /home/waggle/test_node_NC_MMC.log >> $report_file || true
  rm -f /home/waggle/test_node_NC_MMC.log

  mount | grep '/media/test' && true
  if [ $? -eq 1 ]; then
    echo "Mounting alternate boot medium..."
    mount "${OTHER_DISK_DEVICE}p2" /media/test
  fi

  echo >> $report_file
  echo "Node Controller SD Test Results" >> $report_file
  echo "---------------------------------" >> $report_file
  cat /media/test/home/waggle/test_node_NC_SD.log >> $report_file || true
  rm -f /media/test/home/waggle/test_node_NC_SD.log

  umount /media/test
}

# Determine root and alternate boot medium root device paths
. /usr/lib/waggle/core/scripts/detect_disk_devices.sh

start_file=/home/waggle/start_test
finish_file=/home/waggle/finish_test

if [ -e ${start_file} ] ; then
  echo "Found start_test."
  run_tests

  if [ "${CURRENT_DISK_DEVICE_TYPE}" == "SD" ]; then
    echo "Setting boot medium to eMMC..."
    wagman-client bs 0 emmc
    wagman-client bs 1 emmc
  else
    echo "Setting boot medium to sd..."
    wagman-client bs 0 sd
    wagman-client bs 1 sd
  fi

  echo "Creating ${finish_file}..."
  touch ${finish_file}

  echo "Requesting reboot in 60 seconds..."
  wagman-client stop 0 || true

  echo "Removing ${start_file}..."
  rm ${start_file}

  echo "Syncing disk..."
  sync

  echo "Will halt after 60 seconds if Wagman fails to reboot..."
  sleep 60
  halt
elif [ -e ${finish_file} ]; then
  echo "Found ${finish_file}..."

  echo "Generating report.."
  generate_report

  echo "Removing ${finish_file}..."
  rm ${finish_file}
fi
