#!/bin/bash
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

wagman-client eereset
wagman-client reset

wagman client bs 1 sd
wagman client bs 0 sd

wagman client stop 1 90
wagman client stop 0 120
