#!/bin/bash
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

pins="76 77"

export_pins() {
    for p in $pins; do
        echo exporting pin $p

        if [ ! -d /sys/class/gpio/gpio$p ]; then
            echo $p > /sys/class/gpio/export
        fi

        echo out > /sys/class/gpio/gpio$p/direction
    done
}

set_pins() {
    for p in $pins; do
        echo setting pin $p
        echo 0 > /sys/class/gpio/gpio$p/value
    done
}

release_pins() {
    for p in $pins; do
        echo releasing pin $p
        echo 1 > /sys/class/gpio/gpio$p/value
    done
}

cleanup() {
    release_pins
}

export_pins

trap cleanup EXIT INT TERM
release_pins
sleep 1

set_pins
sleep 10
