#!/bin/bash

firmware=$1
port=$2

if [ -z "$firmware" ] || [ -z "$port" ]; then
	echo "usage: $0 firmware port"
	exit 1
fi

resolved_port=$(readlink -f "$port")

stty -f "$resolved_port" 1200
bossac -i -d --port=$(basename $resolved_port) -U true -e -w -v -b $firmware -R
