#!/usr/bin/env python3
from pathlib import Path
import subprocess
import time
import logging

logging.basicConfig(level=logging.INFO)


def call_reset_script():
    try:
        return subprocess.check_call(['/usr/lib/waggle/nodecontroller/scripts/reset-wagman'])
    except FileNotFoundError:
        pass

    try:
        return subprocess.check_call(['/usr/bin/waggle-wagman-power-reset'])
    except FileNotFoundError:
        pass

    raise FileNotFoundError('No wagman reset script found')


def reset_wagman():
    try:
        logging.warning('resetting wagman')
        call_reset_script()
    except Exception:
        logging.exception('reset error')
    else:
        time.sleep(15)
        logging.info('reset ok')


last_device_time = time.monotonic()

while True:
    if Path('/dev/waggle_sysmon').exists():
        logging.info('wagman ok')
        last_device_time = time.monotonic()

    if time.monotonic() - last_device_time > 300:
        reset_wagman()
        last_device_time = time.monotonic()

    time.sleep(15)
