#!/bin/bash

pins="74 75"

export_pins() {
    for p in $pins; do
        echo $p > /sys/class/gpio/export
        echo out > /sys/class/gpio/gpio$p/direction
    done
}

set_pins() {
    for p in $pins; do
        echo 0 > /sys/class/gpio/gpio$p/value
    done
}

release_pins() {
    for p in $pins; do
        echo 1 > /sys/class/gpio/gpio$p/value
    done
}

export_pins
trap release_pins EXIT
release_pins
set_pins
sleep 10
