#!/bin/bash
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

# ensure no lingering version exists
rm -f /tmp/coresense-firmware.bin

cd /usr/lib/waggle/sensors
git show 94c30e90568c6cd7f0c8b42423df03ca29488834:v4/integrated/firmware/bin/firmware.ino.bin > /tmp/coresense-firmware.bin
waggle-coresense-flash-firmware /tmp/coresense-firmware.bin /dev/waggle_coresense

# cleanup
rm -f /tmp/coresense-firmware.bin
