#!/bin/bash
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

waggle-wagman-flash-firmware /usr/lib/waggle/wagman/v4/new/firmware/bin/firmware-4.0.0.bin /dev/waggle_sysmon

for i in seq 10; do
    sleep 1

    if [ -e /dev/waggle_sysmon ]; then
        echo "done"
        exit 0
    fi
done

echo "device taking too long to appear. manually resetting."
waggle-wagman-power-reset
