#!/usr/bin/env python3
from pathlib import Path
import subprocess
import time

def ssh_connection_ok():
    try:
        subprocess.check_output([
            'ssh',
            '-i', '/etc/waggle/key.pem',
            '-o', 'StrictHostKeyChecking=no',
            '-o', 'UserKnownHostsFile=/dev/null',
            'beehive',
            '-p', '20022',
            'date',
        ], timeout=60).decode()
        return True
    except Exception:
        return False


def reset_deadman_trigger():
    print('update deadman trigger', flush=True)
    Path('/run/waggle_deadman_trigger').touch()


while True:
    while not ssh_connection_ok():
        print('waiting for connection', flush=True)
        time.sleep(900)

    start = time.monotonic()
    
    while time.monotonic() - start < 3600:
        reset_deadman_trigger()
        time.sleep(15)
