#!/usr/bin/env python3
from glob import glob
import subprocess
import time

last_connection_time = time.monotonic()

while True:
    if len(glob('/sys/class/net/ppp*')) > 0:
        print('connection ok', flush=True)
        last_connection_time = time.monotonic()
    
    if time.monotonic() - last_connection_time > 300:
        print('resetting connection', flush=True)
        subprocess.check_call(['systemctl', 'restart', 'waggle-wwan.service'])
        last_connection_time = time.monotonic()

    time.sleep(15)
