#!/usr/bin/env python3
from contextlib import suppress
from pathlib import Path
import subprocess
import time


def reset_wagman_v1():
    return subprocess.check_output(['/usr/lib/waggle/nodecontroller/scripts/reset-wagman'])


def reset_wagman_v2():
    return subprocess.check_output(['/usr/bin/waggle-wagman-power-reset'])


def reset_wagman():
    with suppress(FileNotFoundError):
        return reset_wagman_v2()
    with suppress(FileNotFoundError):
        return reset_wagman_v1()
    raise FileNotFoundError('No wagman reset script found')


last_device_time = time.monotonic()

while True:
    if Path('/dev/waggle_sysmon').exists():
        print('wagman ok', flush=True)
        last_device_time = time.monotonic()
    
    if time.monotonic() - last_device_time > 300:
        print('resetting wagman', flush=True)
        reset_wagman()
        time.sleep(15)
        print('reset ok', flush=True)
        last_device_time = time.monotonic()

    time.sleep(15)
