#!/bin/bash

pins="74 75"

export_pins() {
    for p in $pins; do
        echo exporting pin $p

        if [ ! -d /sys/class/gpio/gpio$p ]; then
            echo $p > /sys/class/gpio/export
        fi

        echo out > /sys/class/gpio/gpio$p/direction
    done
}

set_pins() {
    for p in $pins; do
        echo setting pin $p
        echo 0 > /sys/class/gpio/gpio$p/value
    done
}

release_pins() {
    for p in $pins; do
        echo releasing pin $p
        echo 1 > /sys/class/gpio/gpio$p/value
    done
}

cleanup() {
    release_pins
    systemctl start waggle-heartbeat.service
}

systemctl stop waggle-heartbeat.service

export_pins
release_pins
sleep 1

trap cleanup EXIT INT TERM
set_pins
sleep 10
