#!/bin/bash

firmware=$1
port=$2

if [ -z "$firmware" ] || [ -z "$port" ]; then
	echo "usage: $0 firmware port"
	exit 1
fi

resolved_port=$(readlink -f "$port")

# pulse serial port at 1200 to put in flash mode
stty -F "$resolved_port" 1200

# upload firmware binary
bossac -i -d --port=$(basename $resolved_port) -U true -e -w -v -b $firmware -R

# restore to standard wagman baudrate
stty -F "$resolved_port" 57600
