#!/bin/bash
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

scan_lsusb() {
    awk -v prefix="$1" '
function show(s) { print prefix s }
/2341:8037/ { show("wagman_v1") }
/2341:003f/ { show("wagman_v2") }
/2341:003e/ { show("coresense") }
/1bc7:0021/ { show("modem") }
/0d8c:013c/ || /8086:0808/ { show("microphone") }
/05a3:8830/ || /05a3:9830/ { show("camera_top") }
/05a3:9520/ { show("camera_bottom") }
'
}

lsusb | scan_lsusb 'nc/'

if ssh ep true; then
    echo 'nc/ep'
fi

ssh ep lsusb | scan_lsusb 'nc/ep/'
