#!/bin/bash
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

firmware=$1
port=$2

if [ -z "$firmware" ] || [ -z "$port" ]; then
	echo "usage: $0 firmware port"
	exit 1
fi

resolved_port=$(readlink -f "$port")

# pulse serial port at 1200 to put in flash mode. i found the dtr = false
# used by the arduino-cli's method for pulsing the serial line.
python3 -c '
import serial
import sys

with serial.Serial(sys.argv[1], 1200) as ser:
    ser.dtr = False
' $resolved_port

sleep 1

# upload firmware binary
bossac -i -d --port=$(basename $resolved_port) -U true -e -w -v -b $firmware -R

sleep 5

# ensure baud rate set back to standard
python3 -c '
import serial
import sys

with serial.Serial(sys.argv[1], 57600) as ser:
    pass
' $resolved_port
