#!/usr/bin/env python3
from pathlib import Path
import subprocess
import time
import logging

logging.basicConfig(level=logging.INFO)


def update_systemd_watchdog():
    subprocess.check_call(['systemd-notify', 'WATCHDOG=1'])


def ssh_connection_ok():
    try:
        return 'beehive:20022' in subprocess.check_output([
            'ss', '-tr', 'state', 'established']).decode()
    except Exception:
        return False


def reset_reverse_tunnel():
    try:
        subprocess.check_output(
            ['systemctl', 'restart', 'waggle-reverse-tunnel.service'])
    except Exception:
        pass


def reset_deadman_trigger():
    Path('/run/waggle_deadman_trigger').touch()


last_connection_time = time.monotonic()
reset_timeout = time.monotonic()

while True:
    update_systemd_watchdog()

    if ssh_connection_ok():
        logging.info('connection ok')
        last_connection_time = time.monotonic()
        reset_timeout = time.monotonic()
    else:
        left = int(time.monotonic() - last_connection_time)
        logging.warning('no connection for %ss', left)

    # continue updating deadman trigger up to an hour after last connection
    if time.monotonic() - last_connection_time < 3600:
        logging.info('update deadman trigger')
        reset_deadman_trigger()

    # attempt to reset reverse ssh tunnel after 5min of no connectivity
    if time.monotonic() - reset_timeout > 300:
        logging.warning('reset reverse ssh tunnel')
        reset_reverse_tunnel()
        reset_timeout = time.monotonic()

    time.sleep(15)
