#!/usr/bin/python3

import datetime
import os
import os.path
import requests
from signal import *
import socket
import subprocess
import sys
import time
import zmq


############################
##### Helper Functions #####
############################

# Run a command and capture it's output
def run_command(command):
  p = subprocess.Popen(command, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)
  return iter(p.stdout.readline, b'')

# Get the Beehive server hostname
def get_beehive_hostname():
  server_host = ''
  try:
    with open('/etc/waggle/server_host', 'r') as f:
      server_host = f.readline().rstrip()
  except Exception:
    pass
  return server_host

def reset_deadman_trigger():
  file = "/usr/lib/waggle/waggle_image/alive"
  rc = os.system("touch " + file + " > /dev/null 2>&1")
  if rc != 0:
    return False
  
def log_message(message):
  os.system("logger -t wellness " + message)

def subscribe_wagman_status():
  context = zmq.Context()
  socket = context.socket(zmq.SUB)
  socket.setsockopt(zmq.RCVTIMEO, 3000)
  socket.setsockopt(zmq.SUBSCRIBE, b'')
  socket.connect ('ipc:///tmp/zeromq_wagman-pub')
  return socket

def unsubscribe_wagman_status(socket):
  socket.close()

###########################
##### Wellness Checks #####
###########################

# See whether file system recovery to the alternate bood medium
# has completed by checking for the existance of /root/do_recovery
def in_recovery():
  return os.path.isfile('/root/do_recovery')

# Check that there is a "Wireless" device connected to the USB hub
def check_USB_modem():
  output = run_command(['lsusb'])
  for line in output:
    if b"Wireless" in line:
      return True
  return False

# Check that there is an IP address listed in the PPP info of ifconfig
def check_network_interface():
  output = run_command(['ifconfig'])
  have_ppp = False
  have_ip = False
  for line in output:
    if b"Point-to-Point Protocol" in line:
      have_ppp = True
    if b"inet addr:" in line:
      have_ip = True
  return have_ppp and have_ip

# DNS lookup of the Beehive server hostname
def check_beehive_DNS(hostname):
  beehive_ip = ''
  try:
    beehive_ip = socket.gethostbyname(hostname)
  except Exception:
    return False

  return True

# Ping the Beehive server
# The ICMP port is disabled on the beehive servers for external IPs, so
# just check that the beehive web portal is up
def check_beehive_ping(hostname):
  rc = os.system("curl " + hostname + "/api/ > /dev/null 2>&1")
  if rc != 0:
    return False

  return True

# Connect to the local sshd
def check_local_sshd():
  # To test, add "waggle" user to ThinkPad and setup passwordless key
  command = ['ssh -i /usr/lib/waggle/SSL/node/key.pem -x',
             '-o "PasswordAuthentication no"',
             '-o "StrictHostKeyChecking no"',
             '-o "ConnectTimeout 1" waggle@localhost',
             'date > /dev/null 2>&1']
  #print(' '.join(command))
  rc = os.system(' '.join(command))
  if rc != 0:
    return False

  return True


# Connect to the Beehive server's sshd
def check_beehive_sshd(hostname):
  command = ['ssh -i /usr/lib/waggle/SSL/node/key.pem -x',
             '-o "PasswordAuthentication no"',
             '-o "StrictHostKeyChecking no"',
             'root@'+hostname, '-p 20022',
             'date > /dev/null 2>&1']
  #print(' '.join(command))
  rc = os.system(' '.join(command))
  if rc != 0:
    return False

  return True


# Check that we can read any WagMan status messages
def check_wagman_status(socket):
  message = ""
  try:
    while True:
      message = socket.recv_string()
  except zmq.ZMQError:
    pass

  if len(message) == 0:
    return False
  return True

#########################
##### Interventions #####
#########################

def reset_wagman():
  os.system("/usr/lib/waggle/waggle_image/scripts/reset_wagman.sh")


# Human readable names for the tests in the same sequence that they are run
test_names = ['USB Modem', 'Network Interface', 'Beehive DNS', 'Beehive Ping',
              'Local sshd', 'Beehive sshd']

# base_sleep_time = 2  # s
beehive_hostname = get_beehive_hostname()

base_sleep_time = 60  # (seconds)

beehive_check_duration = 1800  # (seconds) 30 minutes
# check Beehive on start up
beehive_check_time = time.time() - beehive_check_duration - 1

wagman_status = subscribe_wagman_status()
last_wagman_status_time = time.time()
max_wagman_silence_duration = 600  # (seconds) 10 minutes

""" ################################## """
""" Clean up when script is terminated """
""" ################################## """
def cleanup(signum, stack_frame):
  unsubscribe_wagman_status(wagman_status)
  quit()
for sig in (SIGINT, SIGQUIT, SIGTERM):
  signal(sig, cleanup)
""" ################################## """

while True:
  current_time = time.time()

  # Recovery status check
  if in_recovery():
    reset_deadman_trigger()
    log_message("Node Controller is performing a file system recovery.")

  # Local checks (done every minute)
  #print("Performing local checks...")
  local_check_results = [check_USB_modem(),
                         check_network_interface(),
                         check_local_sshd()]

  # Beehive checks
  beehive_check_results = []
  print("Performing Beehive checks...")
  if (current_time - beehive_check_time) > beehive_check_duration:
    beehive_check_results = [check_beehive_DNS(beehive_hostname),
                             check_beehive_ping(beehive_hostname),
                             check_beehive_sshd(beehive_hostname),]
    if all(beehive_check_results):
      beehive_check_time = time.time()

  # Reset deadman trigger if all local and Beehive checks have passed
  results = local_check_results + beehive_check_results
  if all(results):
    #print("Resetting deadman trigger...")
    reset_deadman_trigger()
    #print("Node Controller is well.")
    log_message("Node Controller is well.")
  else:
    #print("Logging test failures...")
    log_message("The following tests failed: " + 
                str([n for x,n in zip(results,test_names) if not x]) + "\n")

  # WagMan checks
  print("Performing wagman checks...")
  if check_wagman_status(wagman_status):
    # WagMan is still sending updates
    last_wagman_status_time = time.time()
  else:
    # WagMan stopped sending updates
    current_time = time.time()
    wagman_silence_duration = current_time - last_wagman_status_time
    if wagman_silence_duration >= max_wagman_silence_duration:
      log_message("WagMan is not well. Resetting WagMan...")
      reset_wagman()
      last_wagman_status_time = time.time()

  time.sleep(base_sleep_time)
